version: 2

jobs:
  build:
    docker:
      - image: circleci/node:10

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - npm-{{ arch }}-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - npm-{{ arch }}-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - npm- # used if checksum fails

      - run: npm install

      - save_cache:
          key: npm-{{ arch }}-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - node_modules/

      - run: npm test

      # Tried using npx, but there are weird issues when uploading.
      - run:
          name: codecov
          command: |
            npm install --save-dev codecov
            ./node_modules/.bin/codecov

      - store_test_results:
          path: test-results/jest/

      - store_artifacts:
          path: test-results/
